services:
  hae-mongo:
    container_name: hae-mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - hae_network
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  hae-grafana:
    container_name: hae-grafana
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    user: "0:0"
    restart: unless-stopped
    networks:
      - hae_network
    depends_on:
      - hae-mongo
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=false

  hae-server:
    container_name: hae-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - READ_TOKEN=${READ_TOKEN}
      - WRITE_TOKEN=${WRITE_TOKEN}
    depends_on:
      - hae-mongo
    networks:
      - hae_network
    restart: unless-stopped

  hae-nginx:
    container_name: hae-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - hae-grafana
    networks:
      - hae_network
    command: >
      /bin/sh -c "cat > /etc/nginx/conf.d/default.conf << 'EOF'
      server {
        listen 80;
        server_name stats.villadesgros.com;

        location / {
          proxy_pass http://hae-grafana:3000/public-dashboards/116c57863eca4d5894f258c34f37a066;
          proxy_set_header Host $$host;
          proxy_set_header X-Real-IP $$remote_addr;
          proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $$scheme;
        }
      }
      EOF
      nginx -g 'daemon off;'"

networks:
  hae_network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data:
  mongodb-data:
